name: TEST
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  SET-ENV-VAR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set environment variables
        run: |
          echo "my_var=ahmad" >> $GITHUB_ENV
      - name: test value was added
        run: |
          echo ${{ env.my_var }}
          
  RETRIEVE-ENV-VAR:
    needs: SET-ENV-VAR
    runs-on: ubuntu-latest
    steps:

      - name: get environment variables
        run: |
          echo ${{ env.my_var }}
