name: TEST
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Load environment variables
        id: dotenv
        run: |
          echo "Loading environment variables from .env file..."
          echo "::set-output name=env::$(cat .env)"
        shell: bash
        
      - name: Set environment variables
        run: |
          echo "${{ steps.dotenv.outputs.env }}" >> $GITHUB_ENV

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use environment variables
        run: |
          echo "Variable 1: $VARIABLE1"
          echo "Variable 2: $VARIABLE2"
