name: TEST
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  test-var: "ahmad"
jobs:
  load_env_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Load environment variables
        run: echo "VARIABLE1=BOOM" >> "$GITHUB_OUTPUT"
          
  use_env_vars:
    needs: load_env_vars
    runs-on: ubuntu-latest
    steps:
          
      - name: Use environment variables
        run: |
          echo ${{ needs.load_env_vars.outputs.VARIABLE1 }}
