name: TEST
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  test-var: "ahmad"
jobs:
  load_env_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Load environment variables
        run: cat ${{ .env }} >> $GITHUB_ENV
          
      - name: print environment variables
        run: |
          echo "Variable 1: $VARIABLE1"
          echo "Variable 2: $VARIABLE2"

  use_env_vars:
    needs: load_env_vars
    runs-on: ubuntu-latest
    steps:
      - name: Use environment variables
        run: |
          echo ${{ env.VARIABLE1 }}
          echo ${{ env.test-var }}
