name: TEST
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  test-var: "ahmad"
jobs:
  Capture-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Capture variables
        run: |
          echo "Variable snapshot:"
          env | sort > variables.txt
          cat variables.txt
        id: capture_variables
