name: TEST
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.dotenv.outputs.env.VARIABLE1 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Load environment variables
        id: dotenv
        run: |
          echo "Loading environment variables from .env file..."
          echo "name=ahmad" >> $GITHUB_OUTPUT
        shell: bash
        

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use environment variables
        run: |
          echo ${{ needs.build.outputs.output1}}
