name: TEST
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  load_env_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Load environment variables
        run: |
          while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done < .env

  use_env_vars:
    needs: load_env_vars
    runs-on: ubuntu-latest
    steps:
      - name: Use environment variables
        run: |
          echo "Variable 1: $VARIABLE1"
          echo "Variable 2: $VARIABLE2"
