name: TEST
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  SET-ENV-VAR:
    runs-on: ubuntu-latest
    outputs:
      myVariable: ${{ steps.setEnv.outputs.myVariable }}
    steps:
      - uses: actions/checkout@v3

      - name: set environment variables
        run: |
          echo "::set-output name=myVariable::ahmad"
          
  RETRIEVE-ENV-VAR:
    needs: SET-ENV-VAR
    runs-on: ubuntu-latest
    steps:

      - name: get environment variables
        run: |
          echo ${{ needs.SET-ENV-VAR.outputs.myVariable }}
