name: TEST
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  test-var: "ahmad"
jobs:
  load_env_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: cardinalby/export-env-action@v2
        id: exportStep
        with:
          envFile: '.env'
          expand: 'true'
          
      - name: print environment variables
        run: |
          echo ${{ env.VARIABLE1 }}
          echo ${{ env.VARIABLE2 }}

  use_env_vars:
    needs: load_env_vars
    runs-on: ubuntu-latest
    steps:
          
      - name: Use environment variables
        run: |
          echo ${{ steps.exportStep.outputs.VARIABLE1 }}
